services:
  app:
    build:
      context: . 
      dockerfile: docker/php/Dockerfile
      # production|local
      target: ${APP_ENV:-local} 
    container_name: ${COMPOSE_PROJECT_NAME}_app
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: mysql
      DB_HOST: ${PROJECT_DB_HOST}
      DB_DATABASE: ${PROJECT_DB_DATABASE}
      DB_USERNAME: ${PROJECT_DB_USERNAME}
      DB_PASSWORD: ${PROJECT_DB_PASSWORD}
    volumes:
      - ./backend:/var/www
    networks:
      - web_network
    extra_hosts:
      - "host.docker.internal:host-gateway" # Для работы Xdebug на Linux

  nginx:
    image: nginx:stable-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "${PROJECT_PORT_HTTP}:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      DB_HOST: ${PROJECT_DB_HOST}
      MYSQL_DATABASE: ${PROJECT_DB_DATABASE}
      MYSQL_USER: ${PROJECT_DB_USERNAME}
      MYSQL_PASSWORD: ${PROJECT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}_web_network

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
